### ISSUE TITLE
Create Wiki Pages for array methods

### ISSUE THREAD

**Issue by Sykander** [Sykander/iterable-async#34]
Depends: #30 

Here is the current format for pages: https://github.com/Sykander/iterable-async/wiki/Async-For-Each

Pages that are required:
* Async Find #35 
* Async Find Index #38 
* Async Filter #36 
* Async Map #37 
* Async Array #39

**Comment by zak-zaffar** [comment]
https://github.com/Sykander/iterable-async/wiki/Async-Filter
https://github.com/Sykander/iterable-async/wiki/Async-Find
https://github.com/Sykander/iterable-async/wiki/Async-Find-Index
https://github.com/Sykander/iterable-async/wiki/Async-For-Each
https://github.com/Sykander/iterable-async/wiki/Async-Map

**Comment by Sykander** [comment]
Docs will be generated using JSDoc
